variable "region" {}
variable "vpc_name" {}
variable "env" {}
variable "imagename" {}
variable "instance_type" {}
variable "key" {}
variable "cidr_block" {}
variable "public_subnet_cidr_blocks" {}
variable "private_subnet_cidr_blocks" {}
variable "azs" {}
